name: "Validate Packages"
description: "Scans .NET projects for disallowed packages and package licenses."
author: "DfE RSD"

inputs:
  environment:
    description: "Environment name for validation"
    required: true
  github-token:
    description: 'The GITHUB_TOKEN'
    required: true

runs:
  using: "composite"
  steps:
      - name: Configure Git for long paths
        shell: bash
        run: git config --system core.longpaths true
      
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Add nuget package source
        shell: bash
        run: dotnet nuget add source --username USERNAME --password ${{ inputs.github-token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DFE-Digital/index.json"

      - name: Restore dependencies
        shell: pwsh
        env:
          DOTNET_ROLL_FORWARD: Major
        run: |
          $slnFile = Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object -First 1
          if (-not $slnFile) { throw "No .sln file found" }
          dotnet restore $slnFile.FullName

      - name: Install license tool
        shell: pwsh
        run: dotnet tool install --global nuget-license

      - name: Run package policy validation
        shell: pwsh
        run: |
          $envName = '${{ inputs.environment }}'

          . "${{ github.action_path }}/validate-packages.ps1" `
            -Environment $envName `
            -PolicyFilePath "${{ github.action_path }}/packages-policy.json"

      - name: Run license validation
        shell: pwsh
        env:
          DOTNET_ROLL_FORWARD: Major
        run: |
          $envName = '${{ inputs.environment }}'

          . "${{ github.action_path }}/validate-licenses.ps1" `
            -Environment $envName `
            -PolicyFilePath "${{ github.action_path }}/licenses-policy.json"
