name: Validate Packages

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Validate Packages
        shell: pwsh
        run: |
          $inputEnv = '${{ inputs.environment }}'

          .\.github\scripts\validate-packages.ps1 `
            -Environment $inputEnv `
            -PolicyFilePath ".github/policy/packages-policy.json"
